package proyectofinal;

public enum TipoToken {
    IDENTIFICADOR, NUMBER, STRING,

    // Palabras reservadas
    CLASS, VAR, FUN, FOR, IF, PRINT, RETURN, WHILE, ELSE, OR, AND, TRUE, FALSE, NULL, THIS, SUPER,

    // Caracteres
    DIFERENTE, IGUAL_QUE, MAYOR, MAYOR_IGUAL, MENOR, MENOR_IGUAL, GUION, CRUZ, DIAGONAL, ASTERISCO, ADMIRACION, 
    IGUAL, COMA, PUNTO, PARENTESIS_ABIERTO, PARENTESIS_CERRADO, LLAVE_ABIERTA, LLAVE_CERRADA, PUNTO_COMA, 

    // Final de cadena
    EOF
}

